DROP TABLE BUSINESS_HOURS;
DROP TABLE BUSINESS_CATEGORY;
DROP TABLE NEIGHBOURHOOD;
DROP TABLE BUSINESS;

CREATE TABLE BUSINESS(
BUSINESS_ID VARCHAR(50) PRIMARY KEY,
FULL_ADDRESS VARCHAR(100) NOT NULL,
OPEN VARCHAR(5),
CITY VARCHAR(25)NOT NULL,
REVIEW_COUNT NUMBER(5),
BUSINESS_NAME  VARCHAR(100) NOT NULL,
LONGITUDE NUMBER(5,25) NOT NULL,
STATE VARCHAR(50) NOT NULL,
STARS NUMBER(5),
LATITUDE NUMBER(5,25) NOT NULL,
TYPE VARCHAR(25),
ATRRIBUTES VARCHAR2(2048)
);

CREATE TABLE BUSINESS_HOURS(
BUSINESS_ID VARCHAR(50),
BUSINESS_DAY VARCHAR(25),
BUSINESS_OPEN_TIME TIMESTAMP (6),
BUSINESS_CLOSE_TIME TIMESTAMP (6),
PRIMARY KEY (BUSINESS_ID , BUSINESS_DAY),
FOREIGN KEY (BUSINESS_ID) REFERENCES BUSINESS(BUSINESS_ID)
);

CREATE TABLE BUSINESS_CATEGORY(
BUSINESS_ID VARCHAR(50),
BUSINESS_CATEGORY_NAME VARCHAR(100),
FOREIGN KEY (BUSINESS_ID) REFERENCES BUSINESS(BUSINESS_ID)
);

CREATE TABLE NEIGHBOURHOOD(
BUSINESS_ID VARCHAR(50),
NEIGHBOUR_NAME VARCHAR(100),
FOREIGN KEY (BUSINESS_ID) REFERENCES BUSINESS(BUSINESS_ID)
);

CREATE TABLE YELP_USER(
YELPING_SINCE DATE,
REVIEW_COUNT NUMBER(5),
NAME VARCHAR(20),
USER_ID VARCHAR(50) PRIMARY KEY,
FANS NUMBER(5),
AVERAGE_STARS NUMBER(5),
TYPE VARCHAR(20)
);
CREATE TABLE VOTES(
USER_ID VARCHAR(50),
VOTES NUMBER(1),
USEFUL NUMBER(1),
COOL NUMBER(1),
FOREIGN KEY (USER_ID) REFERENCES YELP_USER(USER_ID)
);
CREATE TABLE REVIEWS(
USER_ID VARCHAR(50) PRIMARY KEY,
REVIEW_ID VARCHAR(50),
STARS NUMBER(4),
DATEE DATE,
TEXT VARCHAR (100),
TYPE VARCHAR(20),
BUSINESS_ID VARCHAR (50),
FOREIGN KEY (BUSINESS_ID) REFERENCES BUSINESS(BUSINESS_ID),
FOREIGN KEY (USER_ID) REFERENCES YELP_USER(USER_ID)
);

CREATE TABLE COMPLIMENTS(
USER_ID VARCHAR(50),
FUNNY NUMBER(5),
COOL NUMBER(5),
WRITER NUMBER(5),
PHOTOS NUMBER(5),
MORE NUMBER(5),
FOREIGN KEY (USER_ID) REFERENCES YELP_USER(USER_ID)
);

